runtime: nodejs12
env: standard

instance_class: F1

automatic_scaling:
  max_instances: 1

resources:
  cpu: .8
  memory_gb: 0.5
  disk_size_gb: 5

#Read Only User
env_variables:
  mongourl: "mongodb+srv://demouser:gOoTz78PWMlAOpGv@mentors.wdpe9.gcp.mongodb.net/ics?retryWrites=true&w=majority"

